spring.application.name=validdoc

# database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/validdoc
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa / hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.hibernate.orm.jdbc.warn=ERROR

# file upload limits (5mb max)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB