spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=WARN
logging.level.com.validdoc=INFO
logging.level.org.hibernate.orm.jdbc.warn=ERROR
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false