CREATE TABLE users (
                       id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50)  NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       role     VARCHAR(20)  NOT NULL,
                       active   BOOLEAN      NOT NULL
);

CREATE UNIQUE INDEX users_username_active_unique ON users (username) WHERE active = true;

CREATE TABLE templates (
                           id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name       VARCHAR(100) NOT NULL,
                           active     BOOLEAN      NOT NULL,
                           page_count INTEGER      NOT NULL
);

CREATE UNIQUE INDEX templates_name_active_unique ON templates (name) WHERE active = true;

CREATE TABLE template_segments (
                                   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   template_id BIGINT           NOT NULL REFERENCES templates (id),
                                   label       VARCHAR(40)      NOT NULL,
                                   page        INTEGER          NOT NULL,
                                   x           DOUBLE PRECISION NOT NULL,
                                   y           DOUBLE PRECISION NOT NULL,
                                   w           DOUBLE PRECISION NOT NULL,
                                   h           DOUBLE PRECISION NOT NULL
);

CREATE INDEX template_segments_template_id_idx ON template_segments (template_id);

CREATE TABLE segment_rules (
                               id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               segment_id BIGINT      NOT NULL REFERENCES template_segments (id),
                               rule_type  VARCHAR(30) NOT NULL,
                               param      INTEGER
);

CREATE INDEX segment_rules_segment_id_idx ON segment_rules (segment_id);

CREATE TABLE document_metadata (
                                   id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   file_name       VARCHAR(255) NOT NULL,
                                   status          VARCHAR(30)  NOT NULL,
                                   language        VARCHAR(10),
                                   template_id     BIGINT       NOT NULL REFERENCES templates (id),
                                   segment_results TEXT,
                                   uploaded_by     BIGINT       NOT NULL REFERENCES users (id),
                                   uploaded_at     TIMESTAMP(6) NOT NULL,
                                   processed_at    TIMESTAMP(6),
                                   purge_at        TIMESTAMP(6),
                                   operator_id     BIGINT REFERENCES users (id),
                                   failure_reason  VARCHAR(255)
);

CREATE INDEX document_metadata_status_idx ON document_metadata (status);
CREATE INDEX document_metadata_uploaded_by_idx ON document_metadata (uploaded_by);
CREATE INDEX document_metadata_uploaded_at_idx ON document_metadata (uploaded_at);
CREATE INDEX document_metadata_purge_at_idx ON document_metadata (purge_at);

CREATE TABLE segment_images (
                                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                document_id BIGINT       NOT NULL,
                                segment_id  BIGINT       NOT NULL,
                                image_data  TEXT         NOT NULL,
                                created_at  TIMESTAMP(6) NOT NULL
);

CREATE INDEX segment_images_document_segment_idx ON segment_images (document_id, segment_id);

CREATE TABLE audit_logs (
                            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            document_id  BIGINT,
                            action       VARCHAR(100) NOT NULL,
                            performed_by VARCHAR(50)  NOT NULL,
                            timestamp    TIMESTAMP(6) NOT NULL
);

CREATE INDEX audit_logs_document_id_idx ON audit_logs (document_id);
CREATE INDEX audit_logs_timestamp_idx ON audit_logs (timestamp);

CREATE TABLE validation_settings (
                                     id                       BIGINT PRIMARY KEY,
                                     retention_days           INTEGER          NOT NULL,
                                     ink_density_threshold    DOUBLE PRECISION NOT NULL,
                                     ocr_confidence_threshold DOUBLE PRECISION NOT NULL,
                                     updated_at               TIMESTAMP(6)     NOT NULL,
                                     updated_by               VARCHAR(50)      NOT NULL
);