ALTER TABLE document_metadata
ALTER COLUMN uploaded_at TYPE TIMESTAMP(6) WITH TIME ZONE USING uploaded_at AT TIME ZONE 'UTC',
    ALTER COLUMN processed_at TYPE TIMESTAMP(6) WITH TIME ZONE USING processed_at AT TIME ZONE 'UTC',
    ALTER COLUMN purge_at TYPE TIMESTAMP(6) WITH TIME ZONE USING purge_at AT TIME ZONE 'UTC';

ALTER TABLE segment_images
ALTER COLUMN created_at TYPE TIMESTAMP(6) WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';

ALTER TABLE audit_logs
ALTER COLUMN timestamp TYPE TIMESTAMP(6) WITH TIME ZONE USING timestamp AT TIME ZONE 'UTC';

ALTER TABLE validation_settings
ALTER COLUMN updated_at TYPE TIMESTAMP(6) WITH TIME ZONE USING updated_at AT TIME ZONE 'UTC';